### ISSUE TITLE
ruby setup: path doesn't exist

### ISSUE THREAD

**Issue by roberthopman** [stripe-samples/saving-card-without-payment#13]
# Bug report

For the ruby setup via the Stripe CLI, in `.env.example`: `STATIC_DIR=../../client` doesn't exist. It should be `STATIC_DIR=../client`

Please advise.

**Comment by cjavilla-stripe** [comment]
@roberthopman this will be different depending on how you install the sample. With git clone, it'll be ../../client with stripe samples create, it'll be `../` you might need to experiment for your environment.

**Comment by roberthopman** [comment]
I fully understand, perhaps this could be mentioned in the readme for future readers, as this took me time to realise.

**Comment by cjavilla-stripe** [comment]
Good idea! Thanks for the feedback and sorry for the lost time.
