### ISSUE TITLE
Stripe for future payments in angular project with Dot Net Core 

### ISSUE THREAD

**Issue by shahabblouch** [stripe-samples/saving-card-without-payment#15]
Hello, I am trying to integrate stripe for future payments in angular project with Dot Net Core . But couldn't find proper solution/example.
Anyone has sample or code snipt.

**Comment by cjavilla-stripe** [comment]
Hey @shahabblouch. Sorry we didn't have an example in .NET. I'll work on building one now. The core is to first Create a customer:

```cs
var options = new CustomerCreateOptions
{
  Description = "My First Test Customer (created for API docs)",
};
var service = new CustomerService();
var customer = service.Create(options);
```

Then pass the ID of that customer to create a SetupIntent:

```cs
var options = new SetupIntentCreateOptions
{
  Customer = customer.Id,
};
var service = new SetupIntentService();
var setupIntent = service.Create(options);
// return the setupIntent or just it's client_secret back to the front end to confirmCardSetup.
```

**Comment by cjavilla-stripe** [comment]
@shahabblouch, added here: https://github.com/stripe-samples/saving-card-without-payment/commit/6eab24cd4d4ac5a55df43c77d6fab2aecaafd5dc

Here's a video walking through it also: https://youtu.be/U_AfLEpUTPs
