### ISSUE TITLE
CC number overlaps with date input on mobile

### ISSUE THREAD

**Issue by bbn** [stripe-samples/saving-card-without-payment#5]
See attached screenshot - this bug more or less makes the sample unusable on mobile. 

The screenshot was taken of https://q0sh7.sse.codesandbox.io/ , the URL linked as a "sample" on https://stripe.com/docs/payments/save-and-reuse.  My phone is a small iPhone 11 Pro.

To reproduce, 
1. go to https://q0sh7.sse.codesandbox.io/
2. enter in the sample CC number 4500 0025 0000 3155.

![IMG_1856](https://user-images.githubusercontent.com/66548/76895432-5c236d80-6866-11ea-8253-32c59ec817cb.PNG)

**Comment by bbn** [comment]
easing up the padding of `.sr-main` helps. but there are still a number of janky rendering bugs as i go through the flow on my phone.

**Comment by mickaelmonsieur** [comment]
i have the same bug.
solution found?

**Comment by mickaelmonsieur** [comment]
Try with remove:
```
fontSize: "16px",
```

**Comment by mickaelmonsieur** [comment]
My proposal does not work in all cases.
Too bad for Stripe to provide examples that don't work.

**Comment by mickaelmonsieur** [comment]
Try this changes:

In the part "@media (max-width: 720px)" 

1. In .sr-root, change "padding: 48px 20px;" to "padding: 48px 10px;"
2. In .sr-main, add : "padding: 50px 10px 75px 10px;"

Optionnaly, in the part "sr-card-element", replace "padding-top: 12px;" with: "padding: 10px; margin-bottom: 2px;"

Works for me for iPhone 5/SE 320x568 in Chrome Debugger.

**Comment by charliegerard-stripe** [comment]
Hey @bbn & @mickaelmonsieur 👋 

Thanks for opening and contributing to this issue and sorry about the delay in getting back to you. I'm merging a PR to fix that now so it should be all good and I'll close this issue.
