### ISSUE TITLE
Problem error: Uncaught (in promise) SyntaxError: Unexpected token g in JSON at position 1

### ISSUE THREAD

**Issue by xguya** [stripe-samples/saving-card-without-payment#9]
I'm using php / nginx / centos 8 /  PHP 7.2.30 
This is output console on chrome:

```
Uncaught (in promise) SyntaxError: Unexpected token g in JSON at position 1
Promise.then (async)
getPublicKey @ script.js:86
(anonymous) @ script.js:121
```

In script.js : 

```
83     .then(function(response) {
84     return response.json();
85   })
86    .then(function(response) {
87      getSetupIntent(response.publicKey);
88    });
```

and
`121 getPublicKey();`

My html form doesn't works, doesn't load, in payment details input info card isn't loaded and I cannot insert card data.

Any idea?

**Comment by SargisParunakyan1** [comment]
Did you solve this?I faced the same issue

**Comment by cjavilla-stripe** [comment]
Can you share the output from the server log? Wondering if the environment variables weren't configured or something. I just tested locally and am unable to reproduce.

**Comment by xguya** [comment]
> Did you solve this?I faced the same issue

No wasn't solved I'm sorry.

**Comment by xguya** [comment]
> Can you share the output from the server log? Wondering if the environment variables weren't configured or something. I just tested locally and am unable to reproduce.

I have just this error in chrome console but no error in my server log: 
 
`
Uncaught (in promise) SyntaxError: Unexpected token g in JSON at position 1
 Promise.then (async)		
getPublicKey	@	script.js:149
(anonymous)	@	script.js:154

`

**Comment by cjavilla-stripe** [comment]
Can you show how you're starting the server? There should be some console output where the server is started. Also, can you look at the network tab in the chrome console to see what the responses look like from the server?

**Comment by xguya** [comment]
What's mean 'how you're starting the server' ?    
I'm using php / nginx / centos 8 / PHP 7.2.30

I don't have other rows in console output. 

I don't know with apache, but with this configuration I have to set absolute urls for css/js

**Comment by cjavilla-stripe** [comment]
okay we'll really need more info to go on than that error message. It's unclear what server side failure is rendering back data that is not valid json.

**Comment by cjavilla-stripe** [comment]
I wasn't able to reproduce with the php sample and the issue is stale, so closing. Feel free to open with some more details if you're still hitting this issue.

**Comment by MHCreations** [comment]
I have a Stripe Support Request ongoing with this exact issue and the cause appears to be incomplete implementation of the server side setting of the variables that are used by the JS "fetch" requests. Some documentation on the github code saying where the fetch items are fetched from (and referencing how they're set up) would be very helpful. It appears the server side code [PHP in my case] should be generating these fetched items dynamically; but there's no documentation that I could find about this.
